### ISSUE TITLE
Running ffmpeg on Windows cause to show console window

### ISSUE THREAD

**Issue by qarmin** [Farmadupe/ffmpeg_cmdline_utils#1]
On Linux there is no issue.

Maybe something like this should work - https://www.robvanderwoude.com/battech_hideconsole.php?

**Comment by Farmadupe** [comment]
[TIL that rust lets you do a windows-specific syscall to hide the console window](https://stackoverflow.com/questions/60750113/how-do-i-hide-the-console-window-for-a-process-started-with-stdprocesscomman). 

The latest commit to main should fix this. Once I've regression tested on Linux, I will push the fix to crates.io in v0.1.1.

**Comment by Farmadupe** [comment]
I have now fixed this issue and pushed updated version v0.1.1 to crates.io. 

A CMD window should not spawn any more when calling into ffmpeg.

**Comment by qarmin** [comment]
Checked that now there is no visible window in WIndows
