### ISSUE TITLE
Add support for image-rs 0.24

### ISSUE THREAD

**Issue by qarmin** [Farmadupe/ffmpeg_cmdline_utils#3]
Currently both 
https://github.com/Farmadupe/ffmpeg_cmdline_utils
and 
https://github.com/Farmadupe/vid_dup_finder_lib

use image-rs 0.23, so app that use image-rs 0.24, must contains code for both versions of this library which increase compilation times and binary size

**Comment by Farmadupe** [comment]
I have published ffmpeg_cmdline_utils v0.1.2 and vid_dup_finder_lib v0.1.1 on crates.io, with dependency on image v0.24.
