### ISSUE TITLE
Add ability to set timeout

### ISSUE THREAD

**Issue by qarmin** [Farmadupe/ffmpeg_cmdline_utils#4]
Looks that currently some files cause freeze at ffmpeg side - https://github.com/qarmin/czkawka/issues/775 so good solution would be to add timeout command to be able to close ffmpeg after a while to prevent such situations

**Comment by Farmadupe** [comment]
I have updated crates ffmpeg_cmdline_utils and vid_dup_finder_lib on github to address this issue. 

I have tested the changes in Linux, but not yet on Windows (I have no access to broken video files so I have to test by spoofing Ffmpeg on every operating system). If the fix also works on windows, I will push the changes to crates.io.

I think no modification is necessary in Czkawka -- only to update the version of ffmpeg_cmdline_utils and vid_dup_finder_lib in Cargo.toml.

**Comment by qarmin** [comment]
When looking at code I think that this may work fine, also when testing everything worked(I also don't have broken video/ffmpeg installation to test it)

The only way to test it in Czkawka on Windows is to update ffmpeg and vid_dup_lib dependencies in CI to produce windows binaries, but looks that due broken https://github.com/Farmadupe/vid_dup_finder_lib/blob/main/Cargo.toml I cannot import and test it.

**Comment by Farmadupe** [comment]
Apologies for the long delay!

I have completed basic windows testing using my cmdline utility. I tested that it can still load video files, but I did not test with any broken video file.

I have updated ffmpeg_cmdline_utils in crates.io to v0.1.2 and I have updated vid_dup_finder_lib to v0.1.1.

I think the only change needed to Czkawka is to update dependencies.

I hope everything works!
